AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: "A Lambda function that searches a movie collection in MongoDB Atlas"
Resources:
  MovieSearchProcessor:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs6.10
      Handler: lambda.handler
      CodeUri: .
      Timeout: 10
      FunctionName: LexMovieSearch
      Description: "A Lambda function that searches a movie collection in MongoDB Atlas"
      Environment:
        Variables:
          MONGODB_URI: "mongodb://YOUR_MONGODB_ATLAS/CONNECTION_STRING"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /moviesearch
            Method: post